version: "3.9"
services:
  ecommerce-bookstore:
    container_name: "ecommerce-bookstore"
    build:
      context: "."
      dockerfile: "./ecommerce-project/Dockerfile"
    environment:
      - "MONGO_URL=mongodb://user:password@mongo:27017/ecommerce-bookstore?authSource=ecommerce-project&w=1"
      - "JWT_SECRET=major_buttkicking_is_back_in_town"
      - "MAILER_EMAIL=matt@example.com"
      - "MAILER_PASSWORD=password"
      - "MAILER_API_KEY=secretkey"
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
    links:
      - "mongo"
    volumes:
      - "./ecommerce-project:/app/cse341-ecommerce/ecommerce-project"
  mongo:
    image: "mongo"
    container_name: "mongo"
    environment:
      - "MONGO_INITDB_DATABASE=ecommerce-project"
      - "MONGO_INITDB_ROOT_USERNAME=user"
      - "MONGO_INITDB_ROOT_PASSWORD=password"
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - "./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro"
      - "./mongo-volume:/data/db"
